version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DS_URL: jdbc:postgresql://postgres:5432/practice
      DS_USERNAME_FILE: /run/secrets/db_username
      DS_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: practice

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    restart: always

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

    secrets:
      - db_username
      - db_password

    environment:
      POSTGRES_DB: practice
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    restart: always

secrets:
  db_username:
    file: ./db_username.txt
  db_password:
    file: ./db_password.txt

volumes:
  data:










